version: '2.4'

services:
  ml_api:
    hostname: ml_api
    restart: unless-stopped
    environment:
      # Set either SNAPSHOT_URL or STREAM_URL. If both set, SNAPSHOT_URL is used
      SNAPSHOT_URL: ${SNAPSHOT_URL}
      STREAM_URL: ${STREAM_URL}
      # MQTT settings
      MQTT_BROKER_IP: ${MQTT_BROKER_IP}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
      MQTT_BROKER_USER: ${MQTT_BROKER_USER}
      MQTT_BROKER_PASSWORD: ${MQTT_BROKER_PASSWORD}
      MQTT_BASE_TOPIC: thenoodlesnoop
      # How often the detection should be run
      SNOOPING_INTERVAL_SEC: 5
      # Adjust sensitivity between 0.8 - 1.2
      DETECTIVE_SENSITIVITY: 1.0
      # Threshold for confidence of detection needed to draw an overlay box
      VISUALIZATION_THRESHOLD: 0.15
      # Hyperparameters for the machine learning model. Consult Obico developer documentation or leave as-is.
      THRESH: 0.08
      THRESHOLD_LOW: 0.38
      THRESHOLD_HIGH: 0.78
      INIT_SAFE_FRAME_NUM: 30
      EWM_ALPHA: 0.1538
      ROLLING_WIN_SHORT: 310
      ROLLING_WIN_LONG: 7200
      ROLLING_MEAN_SHORT_MULTIPLE: 3.8
    build:
      context: ml_api
    tty: true
